# Copyright 2026 Muaaz Bhamjee
# SPDX-License-Identifier: Apache-2.0
"""Sphinx configuration for the fluxlb API reference site.

Division of labour (see CLAUDE.md, "Working mode"): this site is the API reference, built
from the docstrings, plus the roadmap and tutorials. The narrative user guide, including all
theory, lives in LaTeX under ``docs/guide`` and is published here as a PDF only. Do not add
theory prose to these pages.
"""

from __future__ import annotations

import ast
import importlib.metadata
from pathlib import Path

project = "fluxlb"
author = "Muaaz Bhamjee"
copyright = "2026, Muaaz Bhamjee"
try:
    release = importlib.metadata.version("fluxlb")
except importlib.metadata.PackageNotFoundError:  # building without an install
    release = "0.0.0"
version = ".".join(release.split(".")[:2])

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx_autodoc_typehints",
    "myst_parser",
]

source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
exclude_patterns = ["_build", "guide/**", "Thumbs.db", ".DS_Store"]

# Docstrings follow the numpy convention (pyproject: ruff pydocstyle convention = numpy).
napoleon_numpy_docstring = True
napoleon_google_docstring = False
napoleon_use_rtype = False
# Render numpy "Attributes" sections as :ivar: fields. As attribute directives they would
# duplicate the annotated class attributes autodoc already documents (Sphinx -W fails).
napoleon_use_ivar = True

autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
    "member-order": "bysource",
}
autodoc_typehints = "description"
always_document_param_types = True
typehints_use_rtype = False

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "torch": ("https://pytorch.org/docs/stable/", None),
}

myst_enable_extensions = ["dollarmath", "colon_fence", "deflist"]
suppress_warnings = ["myst.header"]  # the roadmap uses H4 under H2 deliberately
myst_heading_anchors = 3

html_theme = "furo"
html_title = "fluxlb"
html_static_path: list[str] = []
html_theme_options = {
    "source_repository": "https://github.com/cerg-flux-lab/fluxlb",
    "source_branch": "main",
    "source_directory": "docs/",
}

# --- API pages ------------------------------------------------------------------------
# Only implemented and tested modules appear in the reference, and "tested" is taken
# literally: a page is generated for every fluxlb module imported by a test under
# tests/unit. The pages are written here, before Sphinx reads the source tree, and are
# git-ignored; api/index.md collects them with a glob toctree. Packages (``__init__``) are
# not documented, only modules.

_DOCS = Path(__file__).resolve().parent
_REPO = _DOCS.parent
_API = _DOCS / "api"
_UNIT_TESTS = _REPO / "tests" / "unit"


def _module_file(dotted: str) -> Path | None:
    """Return the file of a plain ``fluxlb`` module, or ``None`` for anything else."""
    parts = dotted.split(".")
    if parts[0] != "fluxlb":
        return None
    path = _REPO.joinpath(*parts).with_suffix(".py")
    return path if path.is_file() else None


def _tested_modules() -> list[str]:
    """Dotted names of every ``fluxlb`` module imported by a unit test."""
    found: set[str] = set()
    for test in sorted(_UNIT_TESTS.rglob("test_*.py")):
        tree = ast.parse(test.read_text(), filename=str(test))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                found.update(a.name for a in node.names if _module_file(a.name))
            elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
                for alias in node.names:
                    candidate = f"{node.module}.{alias.name}"
                    if _module_file(candidate):
                        found.add(candidate)
                    elif _module_file(node.module):
                        found.add(node.module)
    return sorted(found)


def _write_api_pages() -> None:
    """Regenerate ``docs/api/*.md``, removing pages for modules no longer tested."""
    for stale in _API.glob("*.md"):
        if stale.name != "index.md":
            stale.unlink()
    for dotted in _tested_modules():
        page = _API / f"{dotted.removeprefix('fluxlb.')}.md"
        page.write_text(
            "<!-- Generated by docs/conf.py from the unit tests. Do not edit. -->\n"
            f"# `{dotted}`\n\n"
            "```{eval-rst}\n"
            f".. automodule:: {dotted}\n"
            "```\n"
        )


_write_api_pages()
